name: Build And Release
on:
  push:
    branches: [ master ]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  persist-credentials: false
                  submodules: recursive

            - name: Set branch environment variable
              run: |
                  currentBranch=$(git branch --show-current)
                  now_date=$(date "+%Y-%m-%d_%H-%M-%S")
                  echo "project_branch=${currentBranch}-${now_date}" >> ${GITHUB_ENV}

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Build
              run: |
                  npm install -g yarn
                  yarn cache clean
                  export NODE_OPTIONS=--max-old-space-size=8192
                  export NODE_OPTIONS=--openssl-legacy-provider
                  yarn && yarn docs:build
                  ls docs
                  tar -czvf build.tar.gz docs

            - name: Create GitHub Release
              uses: ncipollo/release-action@v1
              with:
                   tag: ${{ env.project_branch }}
                   allowUpdates: true
                   artifacts: "build.tar.gz"
                   token: ${{ github.token }}
                   generateReleaseNotes: true    
